/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.ndk_demo_lib1;

public class FINFeatureFlagModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public FINFeatureFlagModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FINFeatureFlagModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(FINFeatureFlagModel obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigCallbackDemoJNI.delete_FINFeatureFlagModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(String value) {
    SwigCallbackDemoJNI.FINFeatureFlagModel_id_set(swigCPtr, this, value);
  }

  public String getId() {
    return SwigCallbackDemoJNI.FINFeatureFlagModel_id_get(swigCPtr, this);
  }

  public void setVariant(FINFeatureFlagVariant value) {
    SwigCallbackDemoJNI.FINFeatureFlagModel_variant_set(swigCPtr, this, FINFeatureFlagVariant.getCPtr(value), value);
  }

  public FINFeatureFlagVariant getVariant() {
    long cPtr = SwigCallbackDemoJNI.FINFeatureFlagModel_variant_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FINFeatureFlagVariant(cPtr, true);
  }

  public FINFeatureFlagModel() {
    this(SwigCallbackDemoJNI.new_FINFeatureFlagModel(), true);
  }

}
