/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.observer;




public class TestOptionalBridge {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public TestOptionalBridge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TestOptionalBridge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(TestOptionalBridge obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.observer.ObserverModuleJNI.delete_TestOptionalBridge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEnum1(TestEnum1 value) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestOptionalBridge_enum1_set(swigCPtr, this, value == null ? Integer.MIN_VALUE : value.swigValue());
  }

  public TestEnum1 getEnum1() {
    int value = com.hyh.jnitest.test.observer.ObserverModuleJNI.TestOptionalBridge_enum1_get(swigCPtr, this);
    if (value == Integer.MIN_VALUE) {
        return null;
    } else {
        return TestEnum1.swigToEnum(value);
    }
  }

  public void setEnum11(TestEnum1 value) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestOptionalBridge_enum11_set(swigCPtr, this, value.swigValue());
  }

  public TestEnum1 getEnum11() {
    return TestEnum1.swigToEnum(com.hyh.jnitest.test.observer.ObserverModuleJNI.TestOptionalBridge_enum11_get(swigCPtr, this));
  }

  public TestOptionalBridge() {
    this(com.hyh.jnitest.test.observer.ObserverModuleJNI.new_TestOptionalBridge(), true);
  }

}
