/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.observer;
import com.hyh.jnitest.test.observer.model.*;



public class TestStructVector extends java.util.AbstractList<TestStruct> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public TestStructVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;

    TestStructVector.class.getEnumConstants();

  }

  public static long getCPtr(TestStructVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(TestStructVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.observer.ObserverModuleJNI.delete_TestStructVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TestStructVector(TestStruct[] initialElements) {
    this();
    reserve(initialElements.length);

    for (TestStruct element : initialElements) {
      add(element);
    }
  }

  public TestStructVector(Iterable<TestStruct> initialElements) {
    this();
    for (TestStruct element : initialElements) {
      add(element);
    }
  }

  public TestStruct get(int index) {
    return doGet(index);
  }

  public TestStruct set(int index, TestStruct e) {
    return doSet(index, e);
  }

  public boolean add(TestStruct e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, TestStruct e) {
    modCount++;
    doAdd(index, e);
  }

  public TestStruct remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public TestStructVector() {
    this(com.hyh.jnitest.test.observer.ObserverModuleJNI.new_TestStructVector__SWIG_0(), true);
  }

  public TestStructVector(TestStructVector other) {
    this(com.hyh.jnitest.test.observer.ObserverModuleJNI.new_TestStructVector__SWIG_1(TestStructVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_clear(swigCPtr, this);
  }

  public TestStructVector(int count, TestStruct value) {
    this(com.hyh.jnitest.test.observer.ObserverModuleJNI.new_TestStructVector__SWIG_2(count, TestStruct.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_doSize(swigCPtr, this);
  }

  private void doAdd(TestStruct x) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_doAdd__SWIG_0(swigCPtr, this, TestStruct.getCPtr(x), x);
  }

  private void doAdd(int index, TestStruct x) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_doAdd__SWIG_1(swigCPtr, this, index, TestStruct.getCPtr(x), x);
  }

  private TestStruct doRemove(int index) {
    return new TestStruct(com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_doRemove(swigCPtr, this, index), true);
  }

  private TestStruct doGet(int index) {
    return new TestStruct(com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_doGet(swigCPtr, this, index), false);
  }

  private TestStruct doSet(int index, TestStruct val) {
    return new TestStruct(com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_doSet(swigCPtr, this, index, TestStruct.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStructVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
