/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.observer;
import com.hyh.jnitest.test.observer.model.*;



public class TestStruct2Vector extends java.util.AbstractList<TestStruct2> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public TestStruct2Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TestStruct2Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(TestStruct2Vector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.observer.ObserverModuleJNI.delete_TestStruct2Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TestStruct2Vector(TestStruct2[] initialElements) {
    this();
    reserve(initialElements.length);

    for (TestStruct2 element : initialElements) {
      add(element);
    }
  }

  public TestStruct2Vector(Iterable<TestStruct2> initialElements) {
    this();
    for (TestStruct2 element : initialElements) {
      add(element);
    }
  }

  public TestStruct2 get(int index) {
    return doGet(index);
  }

  public TestStruct2 set(int index, TestStruct2 e) {
    return doSet(index, e);
  }

  public boolean add(TestStruct2 e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, TestStruct2 e) {
    modCount++;
    doAdd(index, e);
  }

  public TestStruct2 remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public TestStruct2Vector() {
    this(com.hyh.jnitest.test.observer.ObserverModuleJNI.new_TestStruct2Vector__SWIG_0(), true);
  }

  public TestStruct2Vector(TestStruct2Vector other) {
    this(com.hyh.jnitest.test.observer.ObserverModuleJNI.new_TestStruct2Vector__SWIG_1(TestStruct2Vector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_clear(swigCPtr, this);
  }

  public TestStruct2Vector(int count, TestStruct2 value) {
    this(com.hyh.jnitest.test.observer.ObserverModuleJNI.new_TestStruct2Vector__SWIG_2(count, TestStruct2.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_doSize(swigCPtr, this);
  }

  private void doAdd(TestStruct2 x) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_doAdd__SWIG_0(swigCPtr, this, TestStruct2.getCPtr(x), x);
  }

  private void doAdd(int index, TestStruct2 x) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_doAdd__SWIG_1(swigCPtr, this, index, TestStruct2.getCPtr(x), x);
  }

  private TestStruct2 doRemove(int index) {
    return new TestStruct2(com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_doRemove(swigCPtr, this, index), true);
  }

  private TestStruct2 doGet(int index) {
    return new TestStruct2(com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_doGet(swigCPtr, this, index), false);
  }

  private TestStruct2 doSet(int index, TestStruct2 val) {
    return new TestStruct2(com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_doSet(swigCPtr, this, index, TestStruct2.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestStruct2Vector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
