/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */



package com.hyh.jnitest.test.observer;





public class TestObserverBridge {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  public TestObserverBridge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TestObserverBridge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.observer.ObserverModuleJNI.delete_TestObserverBridge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestObserverBridge_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestObserverBridge_change_ownership(this, swigCPtr, true);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null || getClass() != obj.getClass()) return false;
    TestObserverBridge other = (TestObserverBridge) obj;
    return this.isEquals(other);
  }

  @Override
  public int hashCode() {
    return this.calculateHash();
  }

  public TestObserverBridge() {
    this(com.hyh.jnitest.test.observer.ObserverModuleJNI.new_TestObserverBridge(), true);
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestObserverBridge_director_connect(this, swigCPtr, true, true);
  }

  public void onCall(int data) {
    com.hyh.jnitest.test.observer.ObserverModuleJNI.TestObserverBridge_onCall(swigCPtr, this, data);
  }

  private int calculateHash() {
    return com.hyh.jnitest.test.observer.ObserverModuleJNI.TestObserverBridge_calculateHash(swigCPtr, this);
  }

  private boolean isEquals(TestObserverBridge other) {
    return com.hyh.jnitest.test.observer.ObserverModuleJNI.TestObserverBridge_isEquals(swigCPtr, this, TestObserverBridge.getCPtr(other), other);
  }

}
