/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.ndk_demo_lib1;

public class FINFeatureFlagVariant {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  public FINFeatureFlagVariant(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FINFeatureFlagVariant obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigCallbackDemoJNI.delete_FINFeatureFlagVariant(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    SwigCallbackDemoJNI.FINFeatureFlagVariant_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return SwigCallbackDemoJNI.FINFeatureFlagVariant_name_get(swigCPtr, this);
  }

  public void setPayload(String value) {
    SwigCallbackDemoJNI.FINFeatureFlagVariant_payload_set(swigCPtr, this, value);
  }

  public String getPayload() {
    return SwigCallbackDemoJNI.FINFeatureFlagVariant_payload_get(swigCPtr, this);
  }

  public FINFeatureFlagVariant() {
    this(SwigCallbackDemoJNI.new_FINFeatureFlagVariant(), true);
  }

}
