/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.ndk_demo_lib1;

public class SwigCallbackFunctionBridge {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  public SwigCallbackFunctionBridge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SwigCallbackFunctionBridge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SwigCallbackDemoJNI.delete_SwigCallbackFunctionBridge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    SwigCallbackDemoJNI.SwigCallbackFunctionBridge_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    SwigCallbackDemoJNI.SwigCallbackFunctionBridge_change_ownership(this, swigCPtr, true);
  }

  public void onCall(SwigCallbackData data) {
    SwigCallbackDemoJNI.SwigCallbackFunctionBridge_onCall(swigCPtr, this, SwigCallbackData.getCPtr(data), data);
  }

  public SwigCallbackFunctionBridge() {
    this(SwigCallbackDemoJNI.new_SwigCallbackFunctionBridge(), true);
    SwigCallbackDemoJNI.SwigCallbackFunctionBridge_director_connect(this, swigCPtr, true, true);
  }

}
