/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.field;




public class BaseFiledKeyVector extends java.util.AbstractList<BaseFiledKey> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public BaseFiledKeyVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BaseFiledKeyVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(BaseFiledKeyVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.field.FieldModuleJNI.delete_BaseFiledKeyVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BaseFiledKeyVector(BaseFiledKey[] initialElements) {
    this();
    reserve(initialElements.length);

    for (BaseFiledKey element : initialElements) {
      add(element);
    }
  }

  public BaseFiledKeyVector(Iterable<BaseFiledKey> initialElements) {
    this();
    for (BaseFiledKey element : initialElements) {
      add(element);
    }
  }

  public BaseFiledKey get(int index) {
    return doGet(index);
  }

  public BaseFiledKey set(int index, BaseFiledKey e) {
    return doSet(index, e);
  }

  public boolean add(BaseFiledKey e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, BaseFiledKey e) {
    modCount++;
    doAdd(index, e);
  }

  public BaseFiledKey remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public BaseFiledKeyVector() {
    this(com.hyh.jnitest.test.field.FieldModuleJNI.new_BaseFiledKeyVector__SWIG_0(), true);
  }

  public BaseFiledKeyVector(BaseFiledKeyVector other) {
    this(com.hyh.jnitest.test.field.FieldModuleJNI.new_BaseFiledKeyVector__SWIG_1(BaseFiledKeyVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_clear(swigCPtr, this);
  }

  public BaseFiledKeyVector(int count, BaseFiledKey value) {
    this(com.hyh.jnitest.test.field.FieldModuleJNI.new_BaseFiledKeyVector__SWIG_2(count, BaseFiledKey.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_doSize(swigCPtr, this);
  }

  private void doAdd(BaseFiledKey x) {
    com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_doAdd__SWIG_0(swigCPtr, this, BaseFiledKey.getCPtr(x), x);
  }

  private void doAdd(int index, BaseFiledKey x) {
    com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_doAdd__SWIG_1(swigCPtr, this, index, BaseFiledKey.getCPtr(x), x);
  }

  private BaseFiledKey doRemove(int index) {
    long cPtr = com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new BaseFiledKey(cPtr, true);
  }

  private BaseFiledKey doGet(int index) {
    long cPtr = com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new BaseFiledKey(cPtr, true);
  }

  private BaseFiledKey doSet(int index, BaseFiledKey val) {
    long cPtr = com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_doSet(swigCPtr, this, index, BaseFiledKey.getCPtr(val), val);
    return (cPtr == 0) ? null : new BaseFiledKey(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    com.hyh.jnitest.test.field.FieldModuleJNI.BaseFiledKeyVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
