/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hyh.jnitest.test.field;


public class FieldModuleJNI {
  public final static native long new_IntLiveDataObserver();
  public final static native void delete_IntLiveDataObserver(long jarg1);
  public final static native void IntLiveDataObserver_onCall(long jarg1, IntLiveDataObserver jarg1_, int jarg2);
  public final static native int IntLiveDataObserver_calculateHash(long jarg1, IntLiveDataObserver jarg1_);
  public final static native boolean IntLiveDataObserver_isEquals(long jarg1, IntLiveDataObserver jarg1_, long jarg2, IntLiveDataObserver jarg2_);
  public final static native void IntLiveDataObserver_director_connect(IntLiveDataObserver obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void IntLiveDataObserver_change_ownership(IntLiveDataObserver obj, long cptr, boolean take_or_release);
  public final static native long new_StringLiveDataObserver();
  public final static native void delete_StringLiveDataObserver(long jarg1);
  public final static native void StringLiveDataObserver_onCall(long jarg1, StringLiveDataObserver jarg1_, String jarg2);
  public final static native int StringLiveDataObserver_calculateHash(long jarg1, StringLiveDataObserver jarg1_);
  public final static native boolean StringLiveDataObserver_isEquals(long jarg1, StringLiveDataObserver jarg1_, long jarg2, StringLiveDataObserver jarg2_);
  public final static native void StringLiveDataObserver_director_connect(StringLiveDataObserver obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void StringLiveDataObserver_change_ownership(StringLiveDataObserver obj, long cptr, boolean take_or_release);
  public final static native long new_OptionalStringLiveDataObserver();
  public final static native void delete_OptionalStringLiveDataObserver(long jarg1);
  public final static native void OptionalStringLiveDataObserver_onCall(long jarg1, OptionalStringLiveDataObserver jarg1_, String jarg2);
  public final static native int OptionalStringLiveDataObserver_calculateHash(long jarg1, OptionalStringLiveDataObserver jarg1_);
  public final static native boolean OptionalStringLiveDataObserver_isEquals(long jarg1, OptionalStringLiveDataObserver jarg1_, long jarg2, OptionalStringLiveDataObserver jarg2_);
  public final static native void OptionalStringLiveDataObserver_director_connect(OptionalStringLiveDataObserver obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void OptionalStringLiveDataObserver_change_ownership(OptionalStringLiveDataObserver obj, long cptr, boolean take_or_release);
  public final static native long new_BaseFiledKeyVector__SWIG_0();
  public final static native long new_BaseFiledKeyVector__SWIG_1(long jarg1, BaseFiledKeyVector jarg1_);
  public final static native boolean BaseFiledKeyVector_isEmpty(long jarg1, BaseFiledKeyVector jarg1_);
  public final static native void BaseFiledKeyVector_clear(long jarg1, BaseFiledKeyVector jarg1_);
  public final static native long new_BaseFiledKeyVector__SWIG_2(int jarg1, long jarg2, BaseFiledKey jarg2_);
  public final static native int BaseFiledKeyVector_doCapacity(long jarg1, BaseFiledKeyVector jarg1_);
  public final static native void BaseFiledKeyVector_doReserve(long jarg1, BaseFiledKeyVector jarg1_, int jarg2);
  public final static native int BaseFiledKeyVector_doSize(long jarg1, BaseFiledKeyVector jarg1_);
  public final static native void BaseFiledKeyVector_doAdd__SWIG_0(long jarg1, BaseFiledKeyVector jarg1_, long jarg2, BaseFiledKey jarg2_);
  public final static native void BaseFiledKeyVector_doAdd__SWIG_1(long jarg1, BaseFiledKeyVector jarg1_, int jarg2, long jarg3, BaseFiledKey jarg3_);
  public final static native long BaseFiledKeyVector_doRemove(long jarg1, BaseFiledKeyVector jarg1_, int jarg2);
  public final static native long BaseFiledKeyVector_doGet(long jarg1, BaseFiledKeyVector jarg1_, int jarg2);
  public final static native long BaseFiledKeyVector_doSet(long jarg1, BaseFiledKeyVector jarg1_, int jarg2, long jarg3, BaseFiledKey jarg3_);
  public final static native void BaseFiledKeyVector_doRemoveRange(long jarg1, BaseFiledKeyVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_BaseFiledKeyVector(long jarg1);
  public final static native long price_get();
  public final static native long name_get();
  public final static native long description_get();
  public final static native void delete_BaseFiledKey(long jarg1);
  public final static native int BaseFiledKey_getKey(long jarg1, BaseFiledKey jarg1_);
  public final static native long new_FieldDataModel(long jarg1, BaseFiledKeyVector jarg1_);
  public final static native long FieldDataModel_getIntFiledValue(long jarg1, FieldDataModel jarg1_, long jarg2, IntFiledKey jarg2_);
  public final static native long FieldDataModel_getStringFiledValue(long jarg1, FieldDataModel jarg1_, long jarg2, StringFiledKey jarg2_);
  public final static native long FieldDataModel_getOptionalStringFiledValue(long jarg1, FieldDataModel jarg1_, long jarg2, OptionalStringFiledKey jarg2_);
  public final static native void delete_FieldDataModel(long jarg1);
  public final static native long new_MutableFieldDataModel(long jarg1, BaseFiledKeyVector jarg1_);
  public final static native long MutableFieldDataModel_getIntFiledValue(long jarg1, MutableFieldDataModel jarg1_, long jarg2, IntFiledKey jarg2_);
  public final static native long MutableFieldDataModel_getStringFiledValue(long jarg1, MutableFieldDataModel jarg1_, long jarg2, StringFiledKey jarg2_);
  public final static native long MutableFieldDataModel_getOptionalStringFiledValue(long jarg1, MutableFieldDataModel jarg1_, long jarg2, OptionalStringFiledKey jarg2_);
  public final static native void delete_MutableFieldDataModel(long jarg1);
  public final static native int IntFiledKey_getKey(long jarg1, IntFiledKey jarg1_);
  public final static native int IntFiledKey_getDefaultValue(long jarg1, IntFiledKey jarg1_);
  public final static native void delete_IntFiledKey(long jarg1);
  public final static native int StringFiledKey_getKey(long jarg1, StringFiledKey jarg1_);
  public final static native String StringFiledKey_getDefaultValue(long jarg1, StringFiledKey jarg1_);
  public final static native void delete_StringFiledKey(long jarg1);
  public final static native int OptionalStringFiledKey_getKey(long jarg1, OptionalStringFiledKey jarg1_);
  public final static native String OptionalStringFiledKey_getDefaultValue(long jarg1, OptionalStringFiledKey jarg1_);
  public final static native void delete_OptionalStringFiledKey(long jarg1);
  public final static native void delete_IntLiveData(long jarg1);
  public final static native long new_IntLiveData(int jarg1);
  public final static native int IntLiveData_GetValue(long jarg1, IntLiveData jarg1_);
  public final static native int IntLiveData_GetValueSwigExplicitIntLiveData(long jarg1, IntLiveData jarg1_);
  public final static native void IntLiveData_AddObserver(long jarg1, IntLiveData jarg1_, long jarg2, IntLiveDataObserver jarg2_, boolean jarg3);
  public final static native void IntLiveData_RemoveObserver(long jarg1, IntLiveData jarg1_, long jarg2, IntLiveDataObserver jarg2_);
  public final static native void IntLiveData_director_connect(IntLiveData obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void IntLiveData_change_ownership(IntLiveData obj, long cptr, boolean take_or_release);
  public final static native void delete_StringLiveData(long jarg1);
  public final static native long new_StringLiveData(String jarg1);
  public final static native String StringLiveData_GetValue(long jarg1, StringLiveData jarg1_);
  public final static native String StringLiveData_GetValueSwigExplicitStringLiveData(long jarg1, StringLiveData jarg1_);
  public final static native void StringLiveData_AddObserver(long jarg1, StringLiveData jarg1_, long jarg2, StringLiveDataObserver jarg2_, boolean jarg3);
  public final static native void StringLiveData_RemoveObserver(long jarg1, StringLiveData jarg1_, long jarg2, StringLiveDataObserver jarg2_);
  public final static native void StringLiveData_director_connect(StringLiveData obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void StringLiveData_change_ownership(StringLiveData obj, long cptr, boolean take_or_release);
  public final static native void delete_OptionalStringLiveData(long jarg1);
  public final static native long new_OptionalStringLiveData(String jarg1);
  public final static native String OptionalStringLiveData_GetValue(long jarg1, OptionalStringLiveData jarg1_);
  public final static native String OptionalStringLiveData_GetValueSwigExplicitOptionalStringLiveData(long jarg1, OptionalStringLiveData jarg1_);
  public final static native void OptionalStringLiveData_AddObserver(long jarg1, OptionalStringLiveData jarg1_, long jarg2, OptionalStringLiveDataObserver jarg2_, boolean jarg3);
  public final static native void OptionalStringLiveData_RemoveObserver(long jarg1, OptionalStringLiveData jarg1_, long jarg2, OptionalStringLiveDataObserver jarg2_);
  public final static native void OptionalStringLiveData_director_connect(OptionalStringLiveData obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void OptionalStringLiveData_change_ownership(OptionalStringLiveData obj, long cptr, boolean take_or_release);
  public final static native long new_MutableIntLiveData(int jarg1);
  public final static native void MutableIntLiveData_SetValue(long jarg1, MutableIntLiveData jarg1_, int jarg2);
  public final static native void delete_MutableIntLiveData(long jarg1);
  public final static native void MutableIntLiveData_director_connect(MutableIntLiveData obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MutableIntLiveData_change_ownership(MutableIntLiveData obj, long cptr, boolean take_or_release);
  public final static native long new_MutableStringLiveData(String jarg1);
  public final static native void MutableStringLiveData_SetValue(long jarg1, MutableStringLiveData jarg1_, String jarg2);
  public final static native void delete_MutableStringLiveData(long jarg1);
  public final static native void MutableStringLiveData_director_connect(MutableStringLiveData obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MutableStringLiveData_change_ownership(MutableStringLiveData obj, long cptr, boolean take_or_release);
  public final static native long new_MutableOptionalStringLiveData(String jarg1);
  public final static native void MutableOptionalStringLiveData_SetValue(long jarg1, MutableOptionalStringLiveData jarg1_, String jarg2);
  public final static native void delete_MutableOptionalStringLiveData(long jarg1);
  public final static native void MutableOptionalStringLiveData_director_connect(MutableOptionalStringLiveData obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MutableOptionalStringLiveData_change_ownership(MutableOptionalStringLiveData obj, long cptr, boolean take_or_release);
  public final static native long MutableFieldDataModel_SWIGUpcast(long jarg1);
  public final static native long IntFiledKey_SWIGSmartPtrUpcast(long jarg1);
  public final static native long StringFiledKey_SWIGSmartPtrUpcast(long jarg1);
  public final static native long OptionalStringFiledKey_SWIGSmartPtrUpcast(long jarg1);
  public final static native long MutableIntLiveData_SWIGSmartPtrUpcast(long jarg1);
  public final static native long MutableStringLiveData_SWIGSmartPtrUpcast(long jarg1);
  public final static native long MutableOptionalStringLiveData_SWIGSmartPtrUpcast(long jarg1);

  public static void SwigDirector_IntLiveDataObserver_onCall(IntLiveDataObserver jself, int value) {
    jself.onCall(value);
  }
  public static void SwigDirector_StringLiveDataObserver_onCall(StringLiveDataObserver jself, String value) {
    jself.onCall(value);
  }
  public static void SwigDirector_OptionalStringLiveDataObserver_onCall(OptionalStringLiveDataObserver jself, String value) {
    jself.onCall(value);
  }
  public static int SwigDirector_IntLiveData_GetValue(IntLiveData jself) {
    return jself.GetValue();
  }
  public static String SwigDirector_StringLiveData_GetValue(StringLiveData jself) {
    return jself.GetValue();
  }
  public static String SwigDirector_OptionalStringLiveData_GetValue(OptionalStringLiveData jself) {
    return jself.GetValue();
  }
  public static int SwigDirector_MutableIntLiveData_GetValue(MutableIntLiveData jself) {
    return jself.GetValue();
  }
  public static String SwigDirector_MutableStringLiveData_GetValue(MutableStringLiveData jself) {
    return jself.GetValue();
  }
  public static String SwigDirector_MutableOptionalStringLiveData_GetValue(MutableOptionalStringLiveData jself) {
    return jself.GetValue();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
