/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hyh.jnitest.test.field;



public class FieldModule {
  public static IntFiledKey getPrice() {
    return new IntFiledKey(FieldModuleJNI.price_get(), true);
  }

  public static StringFiledKey getName() {
    return new StringFiledKey(FieldModuleJNI.name_get(), true);
  }

  public static OptionalStringFiledKey getDescription() {
    return new OptionalStringFiledKey(FieldModuleJNI.description_get(), true);
  }

}
