/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.field;




public class IntLiveData extends IBaseLiveData {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  public IntLiveData(long cPtr, boolean cMemoryOwn) {
    super(com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IntLiveData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        com.hyh.jnitest.test.field.FieldModuleJNI.delete_IntLiveData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_change_ownership(this, swigCPtr, true);
  }

  public IntLiveData(int value) {
    this(com.hyh.jnitest.test.field.FieldModuleJNI.new_IntLiveData(value), true);
    com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_director_connect(this, swigCPtr, true, true);
  }

  public int GetValue() {
    return (getClass() == IntLiveData.class) ? com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_GetValue(swigCPtr, this) : com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_GetValueSwigExplicitIntLiveData(swigCPtr, this);
  }

  public void AddObserver(IntLiveDataObserver observer, boolean immediately) {
    if (getClass() == IntLiveData.class) com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_AddObserver(swigCPtr, this, IntLiveDataObserver.getCPtr(observer), observer, immediately); else com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_AddObserverSwigExplicitIntLiveData(swigCPtr, this, IntLiveDataObserver.getCPtr(observer), observer, immediately);
  }

  public void RemoveObserver(IntLiveDataObserver observer) {
    if (getClass() == IntLiveData.class) com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_RemoveObserver(swigCPtr, this, IntLiveDataObserver.getCPtr(observer), observer); else com.hyh.jnitest.test.field.FieldModuleJNI.IntLiveData_RemoveObserverSwigExplicitIntLiveData(swigCPtr, this, IntLiveDataObserver.getCPtr(observer), observer);
  }

}
