/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.field;




public class MutableIntLiveData extends IntLiveData {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  public MutableIntLiveData(long cPtr, boolean cMemoryOwn) {
    super(com.hyh.jnitest.test.field.FieldModuleJNI.MutableIntLiveData_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MutableIntLiveData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        com.hyh.jnitest.test.field.FieldModuleJNI.delete_MutableIntLiveData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MutableIntLiveData(int value) {
    this(com.hyh.jnitest.test.field.FieldModuleJNI.new_MutableIntLiveData(value), true);
  }

  public void SetValue(int value) {
    com.hyh.jnitest.test.field.FieldModuleJNI.MutableIntLiveData_SetValue(swigCPtr, this, value);
  }

}
