/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.field;




public class MutableOptionalStringLiveData extends OptionalStringLiveData {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  public MutableOptionalStringLiveData(long cPtr, boolean cMemoryOwn) {
    super(com.hyh.jnitest.test.field.FieldModuleJNI.MutableOptionalStringLiveData_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MutableOptionalStringLiveData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        com.hyh.jnitest.test.field.FieldModuleJNI.delete_MutableOptionalStringLiveData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    com.hyh.jnitest.test.field.FieldModuleJNI.MutableOptionalStringLiveData_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    com.hyh.jnitest.test.field.FieldModuleJNI.MutableOptionalStringLiveData_change_ownership(this, swigCPtr, true);
  }

  public MutableOptionalStringLiveData(String value) {
    this(com.hyh.jnitest.test.field.FieldModuleJNI.new_MutableOptionalStringLiveData(value), true);
    com.hyh.jnitest.test.field.FieldModuleJNI.MutableOptionalStringLiveData_director_connect(this, swigCPtr, true, true);
  }

  public void SetValue(String value) {
    com.hyh.jnitest.test.field.FieldModuleJNI.MutableOptionalStringLiveData_SetValue(swigCPtr, this, value);
  }

}
