/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.field;




public class MutableFieldDataModel extends FieldDataModel {
  private transient long swigCPtr;

  public MutableFieldDataModel(long cPtr, boolean cMemoryOwn) {
    super(com.hyh.jnitest.test.field.FieldModuleJNI.MutableFieldDataModel_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MutableFieldDataModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MutableFieldDataModel obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.field.FieldModuleJNI.delete_MutableFieldDataModel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MutableFieldDataModel(BaseFiledKeyVector keys) {
    this(com.hyh.jnitest.test.field.FieldModuleJNI.new_MutableFieldDataModel(BaseFiledKeyVector.getCPtr(keys), keys), true);
  }

  public MutableIntLiveData getIntFiledValue(IntFiledKey key) {
    long cPtr = com.hyh.jnitest.test.field.FieldModuleJNI.MutableFieldDataModel_getIntFiledValue(swigCPtr, this, IntFiledKey.getCPtr(key), key);
    return (cPtr == 0) ? null : new MutableIntLiveData(cPtr, true);
  }

  public MutableStringLiveData getStringFiledValue(StringFiledKey key) {
    long cPtr = com.hyh.jnitest.test.field.FieldModuleJNI.MutableFieldDataModel_getStringFiledValue(swigCPtr, this, StringFiledKey.getCPtr(key), key);
    return (cPtr == 0) ? null : new MutableStringLiveData(cPtr, true);
  }

  public MutableOptionalStringLiveData getOptionalStringFiledValue(OptionalStringFiledKey key) {
    long cPtr = com.hyh.jnitest.test.field.FieldModuleJNI.MutableFieldDataModel_getOptionalStringFiledValue(swigCPtr, this, OptionalStringFiledKey.getCPtr(key), key);
    return (cPtr == 0) ? null : new MutableOptionalStringLiveData(cPtr, true);
  }

}
