/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.field;




public class OptionalStringLiveData {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  public OptionalStringLiveData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OptionalStringLiveData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.field.FieldModuleJNI.delete_OptionalStringLiveData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    com.hyh.jnitest.test.field.FieldModuleJNI.OptionalStringLiveData_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    com.hyh.jnitest.test.field.FieldModuleJNI.OptionalStringLiveData_change_ownership(this, swigCPtr, true);
  }

  public OptionalStringLiveData(String value) {
    this(com.hyh.jnitest.test.field.FieldModuleJNI.new_OptionalStringLiveData(value), true);
    com.hyh.jnitest.test.field.FieldModuleJNI.OptionalStringLiveData_director_connect(this, swigCPtr, true, true);
  }

  public String GetValue() {
    return (getClass() == OptionalStringLiveData.class) ? com.hyh.jnitest.test.field.FieldModuleJNI.OptionalStringLiveData_GetValue(swigCPtr, this) : com.hyh.jnitest.test.field.FieldModuleJNI.OptionalStringLiveData_GetValueSwigExplicitOptionalStringLiveData(swigCPtr, this);
  }

  public void AddObserver(OptionalStringLiveDataObserver observer, boolean immediately) {
    if (getClass() == OptionalStringLiveData.class) com.hyh.jnitest.test.field.FieldModuleJNI.OptionalStringLiveData_AddObserver(swigCPtr, this, OptionalStringLiveDataObserver.getCPtr(observer), observer, immediately); else com.hyh.jnitest.test.field.FieldModuleJNI.OptionalStringLiveData_AddObserverSwigExplicitOptionalStringLiveData(swigCPtr, this, OptionalStringLiveDataObserver.getCPtr(observer), observer, immediately);
  }

  public void RemoveObserver(OptionalStringLiveDataObserver observer) {
    if (getClass() == OptionalStringLiveData.class) com.hyh.jnitest.test.field.FieldModuleJNI.OptionalStringLiveData_RemoveObserver(swigCPtr, this, OptionalStringLiveDataObserver.getCPtr(observer), observer); else com.hyh.jnitest.test.field.FieldModuleJNI.OptionalStringLiveData_RemoveObserverSwigExplicitOptionalStringLiveData(swigCPtr, this, OptionalStringLiveDataObserver.getCPtr(observer), observer);
  }

}
