/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.field;




public class StringLiveData {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  public StringLiveData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StringLiveData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.field.FieldModuleJNI.delete_StringLiveData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    com.hyh.jnitest.test.field.FieldModuleJNI.StringLiveData_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    com.hyh.jnitest.test.field.FieldModuleJNI.StringLiveData_change_ownership(this, swigCPtr, true);
  }

  public StringLiveData(String value) {
    this(com.hyh.jnitest.test.field.FieldModuleJNI.new_StringLiveData(value), true);
    com.hyh.jnitest.test.field.FieldModuleJNI.StringLiveData_director_connect(this, swigCPtr, true, true);
  }

  public String GetValue() {
    return (getClass() == StringLiveData.class) ? com.hyh.jnitest.test.field.FieldModuleJNI.StringLiveData_GetValue(swigCPtr, this) : com.hyh.jnitest.test.field.FieldModuleJNI.StringLiveData_GetValueSwigExplicitStringLiveData(swigCPtr, this);
  }

  public void AddObserver(StringLiveDataObserver observer, boolean immediately) {
    com.hyh.jnitest.test.field.FieldModuleJNI.StringLiveData_AddObserver(swigCPtr, this, StringLiveDataObserver.getCPtr(observer), observer, immediately);
  }

  public void RemoveObserver(StringLiveDataObserver observer) {
    com.hyh.jnitest.test.field.FieldModuleJNI.StringLiveData_RemoveObserver(swigCPtr, this, StringLiveDataObserver.getCPtr(observer), observer);
  }

}
