/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.item;




public class C2NTestItemFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public C2NTestItemFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(C2NTestItemFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(C2NTestItemFactory obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.item.ItemModuleJNI.delete_C2NTestItemFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void init(IC2NTestItemFactory factory) {
    com.hyh.jnitest.test.item.ItemModuleJNI.C2NTestItemFactory_init(IC2NTestItemFactory.getCPtr(factory), factory);
  }

  public static ITestItem create(int index) {
    long ptr = com.hyh.jnitest.test.item.ItemModuleJNI.C2NTestItemFactory_create(index);
    if (ptr == 0) {
      return null;
    } else {
      com.hyh.jnitest.basic.infrastructure.SwigDirectorWrapper wrapper = new com.hyh.jnitest.basic.infrastructure.SwigDirectorWrapper(ptr, true);
      return wrapper.acquire(cPtr -> new ITestItem(cPtr, true));
    }
  }

  public C2NTestItemFactory() {
    this(com.hyh.jnitest.test.item.ItemModuleJNI.new_C2NTestItemFactory(), true);
  }

}
