/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.item;




public class IItemIcon {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  public IItemIcon(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IItemIcon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        com.hyh.jnitest.test.item.ItemModuleJNI.delete_IItemIcon(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    com.hyh.jnitest.test.item.ItemModuleJNI.IItemIcon_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    com.hyh.jnitest.test.item.ItemModuleJNI.IItemIcon_change_ownership(this, swigCPtr, true);
  }

  public String getName() {
    return com.hyh.jnitest.test.item.ItemModuleJNI.IItemIcon_getName(swigCPtr, this);
  }

  public String getIcon() {
    return com.hyh.jnitest.test.item.ItemModuleJNI.IItemIcon_getIcon(swigCPtr, this);
  }

  public IItemIcon() {
    this(com.hyh.jnitest.test.item.ItemModuleJNI.new_IItemIcon(), true);
    com.hyh.jnitest.test.item.ItemModuleJNI.IItemIcon_director_connect(this, swigCPtr, true, true);
  }

}
