/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


package com.hyh.jnitest.test.item;




public class N2CItemIcon extends IItemIcon {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  public N2CItemIcon(long cPtr, boolean cMemoryOwn) {
    super(com.hyh.jnitest.test.item.ItemModuleJNI.N2CItemIcon_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(N2CItemIcon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        com.hyh.jnitest.test.item.ItemModuleJNI.delete_N2CItemIcon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    com.hyh.jnitest.test.item.ItemModuleJNI.N2CItemIcon_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    com.hyh.jnitest.test.item.ItemModuleJNI.N2CItemIcon_change_ownership(this, swigCPtr, true);
  }

  public N2CItemIcon(int index) {
    this(com.hyh.jnitest.test.item.ItemModuleJNI.new_N2CItemIcon(index), true);
    com.hyh.jnitest.test.item.ItemModuleJNI.N2CItemIcon_director_connect(this, swigCPtr, true, true);
  }

  public String getName() {
    return (getClass() == N2CItemIcon.class) ? com.hyh.jnitest.test.item.ItemModuleJNI.N2CItemIcon_getName(swigCPtr, this) : com.hyh.jnitest.test.item.ItemModuleJNI.N2CItemIcon_getNameSwigExplicitN2CItemIcon(swigCPtr, this);
  }

  public String getIcon() {
    return (getClass() == N2CItemIcon.class) ? com.hyh.jnitest.test.item.ItemModuleJNI.N2CItemIcon_getIcon(swigCPtr, this) : com.hyh.jnitest.test.item.ItemModuleJNI.N2CItemIcon_getIconSwigExplicitN2CItemIcon(swigCPtr, this);
  }

}
