/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.jni_test.model;

public class FieldDataModel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public FieldDataModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FieldDataModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(FieldDataModel obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIItemTestJNI.delete_FieldDataModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FieldDataModel(BaseFiledKeyVector keys) {
    this(JNIItemTestJNI.new_FieldDataModel(BaseFiledKeyVector.getCPtr(keys), keys), true);
  }

  public IntLiveData getIntFiledValue(IntFiledKey key) {
    long cPtr = JNIItemTestJNI.FieldDataModel_getIntFiledValue(swigCPtr, this, IntFiledKey.getCPtr(key), key);
    return (cPtr == 0) ? null : new IntLiveData(cPtr, true);
  }

  public StringLiveData getStringFiledValue(StringFiledKey key) {
    long cPtr = JNIItemTestJNI.FieldDataModel_getStringFiledValue(swigCPtr, this, StringFiledKey.getCPtr(key), key);
    return (cPtr == 0) ? null : new StringLiveData(cPtr, true);
  }

  public OptionalStringLiveData getOptionalStringFiledValue(OptionalStringFiledKey key) {
    long cPtr = JNIItemTestJNI.FieldDataModel_getOptionalStringFiledValue(swigCPtr, this, OptionalStringFiledKey.getCPtr(key), key);
    return (cPtr == 0) ? null : new OptionalStringLiveData(cPtr, true);
  }

}
