/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.jni_test.model;

public class JNIItemTest {
  public static IntFiledKey getPrice() {
    return new IntFiledKey(JNIItemTestJNI.price_get(), true);
  }

  public static StringFiledKey getName() {
    return new StringFiledKey(JNIItemTestJNI.name_get(), true);
  }

  public static OptionalStringFiledKey getDescription() {
    return new OptionalStringFiledKey(JNIItemTestJNI.description_get(), true);
  }

}
