/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.jni_test.model;

public class JNITestEntrance {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public JNITestEntrance(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(JNITestEntrance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(JNITestEntrance obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIItemTestJNI.delete_JNITestEntrance(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void testAddObserver(int id) {
    JNIItemTestJNI.JNITestEntrance_testAddObserver(id);
  }

  public static void testRemoveObserver(int id) {
    JNIItemTestJNI.JNITestEntrance_testRemoveObserver(id);
  }

  public JNITestEntrance() {
    this(JNIItemTestJNI.new_JNITestEntrance(), true);
  }

}
