/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.jni_test.model;

public class MutableStringLiveData extends StringLiveData {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  public MutableStringLiveData(long cPtr, boolean cMemoryOwn) {
    super(JNIItemTestJNI.MutableStringLiveData_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MutableStringLiveData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        JNIItemTestJNI.delete_MutableStringLiveData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    JNIItemTestJNI.MutableStringLiveData_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    JNIItemTestJNI.MutableStringLiveData_change_ownership(this, swigCPtr, true);
  }

  public MutableStringLiveData(String value) {
    this(JNIItemTestJNI.new_MutableStringLiveData(value), true);
    JNIItemTestJNI.MutableStringLiveData_director_connect(this, swigCPtr, true, true);
  }

  public void SetValue(String value) {
    JNIItemTestJNI.MutableStringLiveData_SetValue(swigCPtr, this, value);
  }

}
