/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.jni_test.model;

public class ObserverManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ObserverManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ObserverManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ObserverManager obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIItemTestJNI.delete_ObserverManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void init(IObserverManager manager) {
    JNIItemTestJNI.ObserverManager_init(IObserverManager.getCPtr(manager), manager);
  }

  public static void addObserver(TestObserverBridge observer) {
    JNIItemTestJNI.ObserverManager_addObserver(TestObserverBridge.getCPtr(observer), observer);
  }

  public static void removeObserver(TestObserverBridge observer) {
    JNIItemTestJNI.ObserverManager_removeObserver(TestObserverBridge.getCPtr(observer), observer);
  }

  public ObserverManager() {
    this(JNIItemTestJNI.new_ObserverManager(), true);
  }

}
