/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.jni_test.model;

public class OptionalStringLiveDataObserver {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  public OptionalStringLiveDataObserver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OptionalStringLiveDataObserver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIItemTestJNI.delete_OptionalStringLiveDataObserver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    JNIItemTestJNI.OptionalStringLiveDataObserver_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    JNIItemTestJNI.OptionalStringLiveDataObserver_change_ownership(this, swigCPtr, true);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null || getClass() != obj.getClass()) return false;
    OptionalStringLiveDataObserver other = (OptionalStringLiveDataObserver) obj;
    return this.isEquals(other);
  }

  @Override
  public int hashCode() {
    return this.calculateHash();
  }

  public OptionalStringLiveDataObserver() {
    this(JNIItemTestJNI.new_OptionalStringLiveDataObserver(), true);
    JNIItemTestJNI.OptionalStringLiveDataObserver_director_connect(this, swigCPtr, true, true);
  }

  public void onCall(String value) {
    JNIItemTestJNI.OptionalStringLiveDataObserver_onCall(swigCPtr, this, value);
  }

  private int calculateHash() {
    return JNIItemTestJNI.OptionalStringLiveDataObserver_calculateHash(swigCPtr, this);
  }

  private boolean isEquals(OptionalStringLiveDataObserver other) {
    return JNIItemTestJNI.OptionalStringLiveDataObserver_isEquals(swigCPtr, this, OptionalStringLiveDataObserver.getCPtr(other), other);
  }

}
