/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.jni_test.model;

public class OptionalStringLiveData {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  public OptionalStringLiveData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OptionalStringLiveData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIItemTestJNI.delete_OptionalStringLiveData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    JNIItemTestJNI.OptionalStringLiveData_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    JNIItemTestJNI.OptionalStringLiveData_change_ownership(this, swigCPtr, true);
  }

  public OptionalStringLiveData(String value) {
    this(JNIItemTestJNI.new_OptionalStringLiveData(value), true);
    JNIItemTestJNI.OptionalStringLiveData_director_connect(this, swigCPtr, true, true);
  }

  public String GetValue() {
    return (getClass() == OptionalStringLiveData.class) ? JNIItemTestJNI.OptionalStringLiveData_GetValue(swigCPtr, this) : JNIItemTestJNI.OptionalStringLiveData_GetValueSwigExplicitOptionalStringLiveData(swigCPtr, this);
  }

  public void AddObserver(OptionalStringLiveDataObserver observer, boolean immediately) {
    JNIItemTestJNI.OptionalStringLiveData_AddObserver(swigCPtr, this, OptionalStringLiveDataObserver.getCPtr(observer), observer, immediately);
  }

  public void RemoveObserver(OptionalStringLiveDataObserver observer) {
    JNIItemTestJNI.OptionalStringLiveData_RemoveObserver(swigCPtr, this, OptionalStringLiveDataObserver.getCPtr(observer), observer);
  }

}
