/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.jni_test.model;

public class TestObserver2Bridge {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  public TestObserver2Bridge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TestObserver2Bridge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIItemTestJNI.delete_TestObserver2Bridge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    JNIItemTestJNI.TestObserver2Bridge_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    JNIItemTestJNI.TestObserver2Bridge_change_ownership(this, swigCPtr, true);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null || getClass() != obj.getClass()) return false;
    TestObserver2Bridge other = (TestObserver2Bridge) obj;
    return this.isEquals(other);
  }

  @Override
  public int hashCode() {
    return this.calculateHash();
  }

  public TestObserver2Bridge() {
    this(JNIItemTestJNI.new_TestObserver2Bridge(), true);
    JNIItemTestJNI.TestObserver2Bridge_director_connect(this, swigCPtr, true, true);
  }

  public void onCall(TestObserver2Data data) {
    JNIItemTestJNI.TestObserver2Bridge_onCall(swigCPtr, this, TestObserver2Data.getCPtr(data), data);
  }

  private int calculateHash() {
    return JNIItemTestJNI.TestObserver2Bridge_calculateHash(swigCPtr, this);
  }

  private boolean isEquals(TestObserver2Bridge other) {
    return JNIItemTestJNI.TestObserver2Bridge_isEquals(swigCPtr, this, TestObserver2Bridge.getCPtr(other), other);
  }

}
