/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.jni_test.model;

public class TestObserver2Vector extends java.util.AbstractList<TestObserver2Bridge> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public TestObserver2Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TestObserver2Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(TestObserver2Vector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JNIItemTestJNI.delete_TestObserver2Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TestObserver2Vector(TestObserver2Bridge[] initialElements) {
    this();
    reserve(initialElements.length);

    for (TestObserver2Bridge element : initialElements) {
      add(element);
    }
  }

  public TestObserver2Vector(Iterable<TestObserver2Bridge> initialElements) {
    this();
    for (TestObserver2Bridge element : initialElements) {
      add(element);
    }
  }

  public TestObserver2Bridge get(int index) {
    return doGet(index);
  }

  public TestObserver2Bridge set(int index, TestObserver2Bridge e) {
    return doSet(index, e);
  }

  public boolean add(TestObserver2Bridge e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, TestObserver2Bridge e) {
    modCount++;
    doAdd(index, e);
  }

  public TestObserver2Bridge remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public TestObserver2Vector() {
    this(JNIItemTestJNI.new_TestObserver2Vector__SWIG_0(), true);
  }

  public TestObserver2Vector(TestObserver2Vector other) {
    this(JNIItemTestJNI.new_TestObserver2Vector__SWIG_1(TestObserver2Vector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return JNIItemTestJNI.TestObserver2Vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    JNIItemTestJNI.TestObserver2Vector_clear(swigCPtr, this);
  }

  public TestObserver2Vector(int count, TestObserver2Bridge value) {
    this(JNIItemTestJNI.new_TestObserver2Vector__SWIG_2(count, TestObserver2Bridge.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return JNIItemTestJNI.TestObserver2Vector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    JNIItemTestJNI.TestObserver2Vector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return JNIItemTestJNI.TestObserver2Vector_doSize(swigCPtr, this);
  }

  private void doAdd(TestObserver2Bridge x) {
    JNIItemTestJNI.TestObserver2Vector_doAdd__SWIG_0(swigCPtr, this, TestObserver2Bridge.getCPtr(x), x);
  }

  private void doAdd(int index, TestObserver2Bridge x) {
    JNIItemTestJNI.TestObserver2Vector_doAdd__SWIG_1(swigCPtr, this, index, TestObserver2Bridge.getCPtr(x), x);
  }

  private TestObserver2Bridge doRemove(int index) {
    long cPtr = JNIItemTestJNI.TestObserver2Vector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new TestObserver2Bridge(cPtr, true);
  }

  private TestObserver2Bridge doGet(int index) {
    long cPtr = JNIItemTestJNI.TestObserver2Vector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new TestObserver2Bridge(cPtr, true);
  }

  private TestObserver2Bridge doSet(int index, TestObserver2Bridge val) {
    long cPtr = JNIItemTestJNI.TestObserver2Vector_doSet(swigCPtr, this, index, TestObserver2Bridge.getCPtr(val), val);
    return (cPtr == 0) ? null : new TestObserver2Bridge(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    JNIItemTestJNI.TestObserver2Vector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
